"""0004_remove_primary_key_constraint

Revision ID: 29f1ed70066a
Revises: cdd1fc3a5acb
Create Date: 2021-07-15 01:28:14.105366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f1ed70066a'
down_revision = 'cdd1fc3a5acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject_student', 'student_id',
               existing_type=sa.INTEGER())
    op.alter_column('subject_student', 'subject_id',
               existing_type=sa.INTEGER())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject_student', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject_student', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
