"""0001_initial_migration

Revision ID: a4e734ec79be
Revises: 
Create Date: 2021-07-14 14:35:42.517764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e734ec79be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subject_student_student_id_fkey', 'subject_student', type_='foreignkey')
    op.drop_constraint('subject_student_subject_id_fkey', 'subject_student', type_='foreignkey')
    op.create_foreign_key(None, 'subject_student', 'subjects', ['subject_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'subject_student', 'people', ['student_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_student', type_='foreignkey')
    op.drop_constraint(None, 'subject_student', type_='foreignkey')
    op.create_foreign_key('subject_student_subject_id_fkey', 'subject_student', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key('subject_student_student_id_fkey', 'subject_student', 'people', ['student_id'], ['id'])
    # ### end Alembic commands ###
