"""0002_declare_cascade

Revision ID: 50451e1efb66
Revises: a4e734ec79be
Create Date: 2021-07-14 14:54:35.094050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50451e1efb66'
down_revision = 'a4e734ec79be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subject_student_subject_id_fkey', 'subject_student', type_='foreignkey')
    op.drop_constraint('subject_student_student_id_fkey', 'subject_student', type_='foreignkey')
    op.create_foreign_key(None, 'subject_student', 'subjects', ['subject_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.create_foreign_key(None, 'subject_student', 'people', ['student_id'], ['id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_student', type_='foreignkey')
    op.drop_constraint(None, 'subject_student', type_='foreignkey')
    op.create_foreign_key('subject_student_student_id_fkey', 'subject_student', 'people', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('subject_student_subject_id_fkey', 'subject_student', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
