"""empty message

Revision ID: aab1e33e3571
Revises: 29f1ed70066a
Create Date: 2021-07-19 14:37:10.515641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab1e33e3571'
down_revision = '29f1ed70066a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject_student', 'student_id',
               existing_type=sa.INTEGER())
    op.alter_column('subject_student', 'subject_id',
               existing_type=sa.INTEGER())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subject_student', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subject_student', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
