"""0003_test_default_delete

Revision ID: cdd1fc3a5acb
Revises: 50451e1efb66
Create Date: 2021-07-15 00:12:44.756167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd1fc3a5acb'
down_revision = '50451e1efb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subject_student_subject_id_fkey', 'subject_student', type_='foreignkey')
    op.drop_constraint('subject_student_student_id_fkey', 'subject_student', type_='foreignkey')
    op.create_foreign_key(None, 'subject_student', 'people', ['student_id'], ['id'])
    op.create_foreign_key(None, 'subject_student', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject_student', type_='foreignkey')
    op.drop_constraint(None, 'subject_student', type_='foreignkey')
    op.create_foreign_key('subject_student_student_id_fkey', 'subject_student', 'people', ['student_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('subject_student_subject_id_fkey', 'subject_student', 'subjects', ['subject_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
